spring.application.name=PruebaChakray
server.port = 9006
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=System
spring.datasource.password=12345
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
logging.level.org.springframework.security=DEBUG

spring.security.user.name=admin
spring.security.user.password=admin123